# See documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
    rebase-strategy: auto
    open-pull-requests-limit: 20
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
      timezone: "America/Montreal"
    ignore:
      # Don't bump these to 9.x.y, as those versions may not be totally compatible with .NET 6 or 8
      - dependency-name: "Microsoft.AspNetCore.WebUtilities"
      - dependency-name: "Microsoft.Bcl.AsyncInterfaces"
      - dependency-name: "System.Text.Json"
      # The following should not be bumped until we use .NET 9+, otherwise we'll get
      #   error CS8032: Could not load file or assembly 'System.Collections.Immutable, Version=9.0.0.0
      - dependency-name: "Microsoft.CodeAnalysis.BannedApiAnalyzers"
      - dependency-name: "Microsoft.CodeAnalysis.PublicApiAnalyzers"
      # LibGit2Sharp 0.31.0+ no longer targets net6.0
      - dependency-name: "LibGit2Sharp"
    rebase-strategy: auto
    open-pull-requests-limit: 20
    groups:
      code-analyzers:
        patterns:
          - "*Analyzer*"
      ms-dependencies:
        patterns:
          - "Microsoft.*"
          - "System.*"
        exclude-patterns:
          - "Microsoft.Playwright"
      test-dependencies:
        patterns:
          - "coverlet.collector"
          - "Microsoft.Playwright"
          - "NSubstitute"
          - "*NUnit*"
